/**
 * MCP resources — the bridge's state exposed as readable documents.
 *
 * Tools are for doing; resources are for reading. A client (or a human in
 * Studio's Resources tab) can pull the manifest, the knowledge graph or the
 * skill registry without invoking anything that mutates state.
 */
import { Injectable, ResourceDecorator as Resource, ExecutionContext } from '@nitrostack/core';
import * as fs from 'fs';
import * as path from 'path';
import { StoreService } from '../../shared/services/store.service.js';
import { WorkspaceService } from '../../shared/services/workspace.service.js';
import { ManifestService } from '../synthesis/manifest.service.js';

@Injectable({ deps: [StoreService, WorkspaceService, ManifestService] })
export class BridgeResources {
  constructor(
    private store: StoreService,
    private workspace: WorkspaceService,
    private manifest: ManifestService
  ) {}

  @Resource({
    uri: 'bridge://manifest/claude-md',
    name: 'CLAUDE.md manifest',
    description:
      'The generated context manifest. Reads the file from disk if it exists, otherwise ' +
      'renders it live from the current knowledge base.',
    mimeType: 'text/markdown',
    examples: { response: '# CLAUDE.md\n\n> Generated by the Enterprise Agentic Bridge…' },
  })
  async getManifest(uri: string, ctx: ExecutionContext) {
    const file = path.join(this.workspace.projectRoot, 'CLAUDE.md');
    let text: string;

    if (fs.existsSync(file)) {
      text = fs.readFileSync(file, 'utf8');
    } else if (this.store.all('knowledge').length) {
      const run = this.store.latestRun();
      const target = run ? path.resolve(this.workspace.projectRoot, run.target) : this.workspace.fixtureRoot;
      text = this.manifest.render(target);
    } else {
      text =
        '# CLAUDE.md\n\n_Not generated yet._\n\n' +
        'Run the `run_swarm` tool to analyse a codebase, then `synthesize_claude_md`.\n';
    }

    ctx.logger.info('Manifest resource read', { bytes: Buffer.byteLength(text) });
    return { contents: [{ uri, mimeType: 'text/markdown', text }] };
  }

  @Resource({
    uri: 'bridge://knowledge/graph',
    name: 'Unified knowledge graph',
    description:
      'Every fact the swarm extracted, grouped by category, with the agent that produced it ' +
      'and the evidence backing it.',
    mimeType: 'application/json',
    examples: { response: { factCount: 41, categories: { architecture: 8, testing: 9 } } },
  })
  async getKnowledgeGraph(uri: string, ctx: ExecutionContext) {
    const facts = this.store.all('knowledge');
    const categories: Record<string, number> = {};
    const agents: Record<string, number> = {};
    for (const f of facts) {
      categories[f.category] = (categories[f.category] ?? 0) + 1;
      agents[f.agent] = (agents[f.agent] ?? 0) + 1;
    }

    ctx.logger.info('Knowledge graph resource read', { facts: facts.length });

    return {
      contents: [
        {
          uri,
          mimeType: 'application/json',
          text: JSON.stringify(
            {
              factCount: facts.length,
              categories,
              agents,
              facts: facts.sort((a, b) => b.weight - a.weight),
            },
            null,
            2
          ),
        },
      ],
    };
  }

  @Resource({
    uri: 'bridge://skills/registry',
    name: 'Generated skill registry',
    description:
      'The MCP tools the swarm minted for this specific codebase, with their parameters, ' +
      'rationale and source file on disk.',
    mimeType: 'application/json',
    examples: { response: { skillCount: 1, skills: [{ name: 'query_aurora_orm' }] } },
  })
  async getSkillRegistry(uri: string) {
    const skills = this.store.all('skills');
    return {
      contents: [
        {
          uri,
          mimeType: 'application/json',
          text: JSON.stringify(
            {
              skillCount: skills.length,
              skillsDirectory: this.workspace.rel(this.workspace.projectRoot, this.workspace.skillsRoot),
              skills,
            },
            null,
            2
          ),
        },
      ],
    };
  }

  @Resource({
    uri: 'bridge://conflicts',
    name: 'Context conflicts',
    description:
      'Every disagreement detected between the ticket tracker and human consensus, with the ' +
      'alignment and divergence scores, and the administrator ruling where one exists.',
    mimeType: 'application/json',
    examples: { response: { conflictCount: 1, openCount: 0 } },
  })
  async getConflicts(uri: string) {
    const conflicts = this.store.all('conflicts');
    return {
      contents: [
        {
          uri,
          mimeType: 'application/json',
          text: JSON.stringify(
            {
              conflictCount: conflicts.length,
              openCount: conflicts.filter((c) => c.status === 'open').length,
              resolvedCount: conflicts.filter((c) => c.status === 'resolved').length,
              conflicts,
            },
            null,
            2
          ),
        },
      ],
    };
  }

  @Resource({
    uri: 'bridge://runs/latest',
    name: 'Latest swarm run',
    description: 'Per-agent status, timings and outcome of the most recent reconnaissance run.',
    mimeType: 'application/json',
    examples: { response: { runId: 'run-1', status: 'completed' } },
  })
  async getLatestRun(uri: string) {
    const run = this.store.latestRun();
    return {
      contents: [
        {
          uri,
          mimeType: 'application/json',
          text: JSON.stringify(run ?? { message: 'No swarm run yet. Call run_swarm.' }, null, 2),
        },
      ],
    };
  }
}
