/**
 * CLAUDE.md synthesis.
 *
 * The manifest is the whole point of the bridge: one deterministic artifact
 * that a fresh Claude instance reads on startup and instantly inherits the
 * team's structure, conventions and unwritten decisions.
 *
 * It is generated from the knowledge base with zero LLM calls. That is a
 * deliberate choice, not a shortcut:
 *   - it is reproducible — same repo in, byte-identical manifest out;
 *   - it cannot hallucinate a coverage threshold or invent a component;
 *   - every claim carries its evidence path, so a human can verify any line;
 *   - it works offline, instantly, with no API key and no rate limit.
 *
 * `enrich_with_llm` exists separately for teams who want narrative prose layered
 * on top. The manifest is correct without it.
 */
import { Injectable } from '@nitrostack/core';
import * as fs from 'fs';
import * as path from 'path';
import { StoreService } from '../../shared/services/store.service.js';
import { WorkspaceService } from '../../shared/services/workspace.service.js';
import type { Conflict, KnowledgeFact } from '../../shared/schemas/index.js';

@Injectable({ deps: [StoreService, WorkspaceService] })
export class ManifestService {
  constructor(
    private store: StoreService,
    private workspace: WorkspaceService
  ) {}

  /** Render the manifest. Pure — takes state, returns a string. */
  render(target: string): string {
    const facts = this.store.all('knowledge');
    const skills = this.store.all('skills');
    const conflicts = this.store.all('conflicts');
    const documents = this.store.all('documents');
    const run = this.store.latestRun();

    const byId = (id: string) => facts.find((f) => f.id === id);
    const byPrefix = (prefix: string) =>
      facts.filter((f) => f.id.startsWith(prefix)).sort((a, b) => b.weight - a.weight);
    const cat = (c: KnowledgeFact['category']) =>
      facts.filter((f) => f.category === c).sort((a, b) => b.weight - a.weight);

    const out: string[] = [];
    const push = (...lines: string[]) => out.push(...lines);

    /* ------------------------------- header ------------------------------- */
    push(
      '# CLAUDE.md',
      '',
      '> **Generated by the Enterprise Agentic Bridge.** Do not edit by hand — re-run',
      '> `synthesize_claude_md` instead. Every claim below was extracted from this repository',
      '> or from a decision a human explicitly validated; evidence paths are cited inline.',
      '',
      `- **Target:** \`${target}\``,
      `- **Generated:** ${new Date().toISOString()}`,
      `- **Knowledge facts:** ${facts.length}`,
      `- **Generated skills:** ${skills.length}`,
      `- **Conflicts:** ${conflicts.length} detected, ${conflicts.filter((c) => c.status === 'resolved').length} resolved by a human`,
      run ? `- **Source run:** \`${run.id}\` (${run.status})` : '',
      ''
    );

    /* ---------------- executive briefing (master orchestrator) ---------------- */
    const briefing = byId('llm:orchestrator:briefing');
    if (briefing) {
      push(
        '## Executive briefing',
        '',
        '_Authored by the master orchestrator over the swarm\'s knowledge base. Everything below',
        'is either extracted evidence or a human ruling; this section is the one place in the',
        'document that is genuinely reasoned._',
        '',
        briefing.detail.trim(),
        ''
      );
    }

    /* ------------------- 0. authoritative human decisions ------------------- */
    const resolved = conflicts.filter((c) => c.status === 'resolved' && c.resolution);
    if (resolved.length) {
      push(
        '## 0. Authoritative decisions (human-validated)',
        '',
        'These override anything else in this document, in the ticket tracker, or in the code.',
        'Each one is a conflict between written and spoken sources that an administrator',
        'personally adjudicated.',
        ''
      );
      for (const c of resolved) {
        push(
          `### ${c.topic}`,
          '',
          `**Ruling:** ${c.resolution!.directive}`,
          '',
          `<sub>Resolved by \`${c.resolution!.resolvedBy}\` at ${c.resolution!.resolvedAt}. ` +
            `Conflict was \`${c.kind}\` — alignment ${c.similarity}, divergence ${c.divergence}. ` +
            `Sources: ${c.sourceA.origin} (${c.sourceA.ref}) vs ${c.sourceB.origin}.</sub>`,
          ''
        );
      }
    }

    const unresolved = conflicts.filter((c) => c.status === 'open');
    if (unresolved.length) {
      push(
        '> ⚠️ **UNRESOLVED CONTEXT CONFLICTS.** The sources below disagree and no human has',
        '> ruled yet. Do not act on either side of these until they are resolved —',
        '> call `resolve_conflict`, or use the conflict-resolver widget.',
        ''
      );
      for (const c of unresolved) {
        push(
          `- **${c.topic}** — ${c.sourceA.origin} (${c.sourceA.ref}) says one thing; ` +
            `${c.sourceB.origin} says another. Machine suggestion: source **${c.recommendation.toUpperCase()}**.`
        );
      }
      push('');
    }

    /* --------------------- 1. architectural topography --------------------- */
    push('## 1. Architectural topography', '');
    const topography = byId('arch:topography');
    if (topography) push(`**Layer distribution:** ${topography.detail}`, '');

    const tree = byId('arch:tree');
    if (tree) push('```', tree.detail, '```', '');

    const hotspots = byPrefix('arch:hotspot:');
    if (hotspots.length) {
      push(
        '### Files with the widest blast radius',
        '',
        'Changing any of these requires reviewing every dependent. Use `find_change_surface`',
        'before you touch one.',
        ''
      );
      for (const h of hotspots) push(`- ${h.detail}`);
      push('');
    }

    const cycles = byId('arch:cycles');
    if (cycles) push('### Import cycles', '', '```', cycles.detail, '```', '');

    /* ----------------------- 2. tailored skills ----------------------- */
    push('## 2. Available tailored skills', '');
    if (skills.length) {
      push(
        'The swarm generated these MCP tools specifically for this codebase. Prefer them over',
        'reading source files by hand — they encode how this project actually works.',
        ''
      );
      for (const s of skills) {
        push(
          `### \`${s.name}\``,
          '',
          s.description,
          '',
          s.params.length
            ? '| Parameter | Type | Required | Description |\n| --- | --- | --- | --- |\n' +
              s.params.map((p) => `| \`${p.name}\` | ${p.type} | ${p.required ? 'yes' : 'no'} | ${p.description} |`).join('\n')
            : '_No parameters._',
          '',
          s.rationale ? `**Why it exists:** ${s.rationale}` : '',
          `<sub>Source: \`${s.sourceFile}\`</sub>`,
          ''
        );
      }
    } else {
      push(
        '_None yet._ When you find a legacy interface that deserves a programmatic tool,',
        'call `generate_custom_skill` — it mints a real MCP tool and registers it live.',
        ''
      );
    }

    /* --------------------- 3. current human alignment --------------------- */
    push('## 3. Current human alignment', '');
    const sprint = byId('agile:sprint');
    if (sprint) push(`**${sprint.title}.** ${sprint.detail}`, '');

    const issues = byPrefix('agile:issue:');
    if (issues.length) {
      push('### In flight right now — do not duplicate this work', '');
      for (const i of issues) push(`- **${i.title}**  \n  ${this.oneLine(i.detail)}`);
      push('');
    }

    const consensus = cat('consensus').filter((f) => !f.id.startsWith('consensus:resolution:'));
    const meeting = consensus.find((f) => f.id === 'consensus:meeting');
    const directives = consensus.filter((f) => f.id.startsWith('consensus:decision-'));
    if (directives.length) {
      push(
        '### Verbal decisions not reflected in the tracker',
        '',
        meeting ? `_Source: ${meeting.title}. ${meeting.detail}_` : '',
        ''
      );
      for (const d of directives) push(`- **${d.title}**  \n  ${this.oneLine(d.detail)}`);
      push('');
    }

    /* -------------------- 4. cultural and syntactic rigor -------------------- */
    push('## 4. Cultural and syntactic rigor', '');

    const commit = byId('cicd:commit-convention');
    if (commit) push('### Commit messages', '', commit.detail, '', this.evidence(commit), '');

    const testing = cat('testing');
    const frameworks = testing.find((t) => t.id === 'qa:frameworks');
    const gate = testing.find((t) => t.id === 'qa:coverage-gate');
    const naming = testing.find((t) => t.id === 'qa:naming');
    if (frameworks || gate || naming) {
      push('### Testing', '');
      if (frameworks) push('```', frameworks.detail, '```', '');
      if (naming) push(`- ${naming.detail}`);
      if (gate) push(`- **${gate.detail}**`);
      push('');
    }

    const lint = testing.filter((t) => t.id.startsWith('qa:lint:'));
    const formatter = testing.find((t) => t.id === 'qa:formatter');
    if (lint.length || formatter) {
      push('### Code style (CI-enforced)', '');
      for (const l of lint) push(`- **${l.title}**: ${l.detail}`);
      if (formatter) push(`- **${formatter.title}**: ${formatter.detail}`);
      push('');
    }

    const policies = testing.filter((t) => t.id.startsWith('qa:policy:'));
    if (policies.length) {
      push('### Written engineering policy', '');
      for (const p of policies) push(`- ${p.detail}`);
      push('');
    }

    const pipelines = cat('cicd').filter((f) => f.id.startsWith('cicd:pipeline:'));
    const branches = byId('cicd:branch-model');
    const gates = byId('cicd:approval-gates');
    if (pipelines.length || branches || gates) {
      push('### Delivery pipeline', '');
      for (const p of pipelines) push(`- **${p.title}** — ${p.detail}`);
      if (branches) push(`- **Branch model** — ${branches.detail}`);
      if (gates) push(`- **Approval gates** — ${gates.detail}`);
      push('');
    }

    const deps = cat('dependency');
    const aging = deps.filter((d) => d.id.startsWith('dep:aging:'));
    const inventory = byId('dep:inventory');
    if (inventory || aging.length) {
      push('### Dependency reality', '');
      if (inventory) push(`- ${inventory.detail}`);
      if (aging.length) {
        push('- **Pinned behind current practice — do not generate code against newer APIs:**');
        for (const a of aging) push(`  - \`${a.title.replace('Pinned old: ', '')}\` — ${a.detail}`);
      }
      push('');
    }

    /* --------------------- 5. design system adherence --------------------- */
    push('## 5. Design system adherence', '');
    const design = cat('design-system');
    if (design.length) {
      const palette = design.find((d) => d.id === 'ui:palette');
      const typography = design.find((d) => d.id === 'ui:typography');
      const components = design.find((d) => d.id === 'ui:components');
      const scale = design.find((d) => d.id === 'ui:scale');
      const conventions = design.filter((d) => d.id.startsWith('ui:convention:'));

      if (palette) push('### Colour', '', '```', palette.detail, '```', '');
      if (typography) push('### Typography', '', '```', typography.detail, '```', '');
      if (scale) push('### Spacing, radius, motion', '', '```', scale.detail, '```', '');
      if (components) push('### Component inventory', '', '```', components.detail, '```', '');
      for (const c of conventions) push(`> ${c.detail}`, '');
    } else {
      push('_No design system detected in this target._', '');
    }

    /* ------------------- reasoned insights (per persona) ------------------- */
    const reasoned = facts
      .filter((f) => f.reasoned && f.id.startsWith('llm:') && !f.id.startsWith('llm:orchestrator'))
      .sort((a, b) => b.weight - a.weight);
    if (reasoned.length) {
      push(
        '## Reasoned insights (per persona)',
        '',
        '_Judgement layered on top of the extracted evidence by each specialist agent. Distinct',
        'from parser output — evaluate accordingly._',
        ''
      );
      const byAgent = new Map<string, KnowledgeFact[]>();
      for (const f of reasoned) {
        const list = byAgent.get(f.agent) ?? [];
        list.push(f);
        byAgent.set(f.agent, list);
      }
      for (const [agent, list] of byAgent) {
        push(`### ${agent}`, '');
        for (const f of list) {
          const evidence = f.evidence.length ? ` <sub>(${f.evidence.map((e) => `\`${e}\``).join(', ')})</sub>` : '';
          push(`- **${f.title}** — ${this.oneLine(f.detail)}${evidence}`);
        }
        push('');
      }
    }

    /* ------------------------- manual context ------------------------- */
    const manual = cat('manual');
    if (manual.length) {
      push('## 6. Manually injected context', '');
      push(
        `${documents.length} document(s) uploaded by an administrator, because the automated`,
        'swarm could not reach them.',
        ''
      );
      for (const m of manual) push(`- **${m.title}** — ${this.oneLine(m.detail)}`);
      push('');
    }

    /* ------------------------------ footer ------------------------------ */
    push(
      '---',
      '',
      '## How to use this document',
      '',
      '1. **Read section 0 first.** Those are human rulings and they beat everything else.',
      '2. Before changing a file, run `find_change_surface` to see what depends on it.',
      '3. Before writing UI, use the components and tokens in section 5 — never invent a hex value.',
      '4. Before committing, re-read the commit convention in section 4. CI enforces it.',
      '5. Ask the knowledge base directly with `query_knowledge` rather than grepping blindly.',
      ''
    );

    return out.filter((line) => line !== undefined).join('\n').replace(/\n{3,}/g, '\n\n');
  }

  private oneLine(text: string): string {
    return text.replace(/\s*\n\s*/g, ' ').trim();
  }

  private evidence(fact: KnowledgeFact): string {
    return fact.evidence.length ? `<sub>Evidence: ${fact.evidence.map((e) => `\`${e}\``).join(', ')}</sub>` : '';
  }

  /** Write the manifest to disk and return the absolute path. */
  write(target: string, outputPath?: string): { path: string; bytes: number; content: string } {
    const content = this.render(target);
    const file = outputPath
      ? path.resolve(outputPath)
      : path.join(this.workspace.projectRoot, 'CLAUDE.md');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, 'utf8');
    return { path: file, bytes: Buffer.byteLength(content, 'utf8'), content };
  }

  /** Conflicts still blocking a clean synthesis. */
  blockingConflicts(): Conflict[] {
    return this.store.all('conflicts').filter((c) => c.status === 'open');
  }
}
